### ISSUE TITLE
Feature requests for `curies.chain()`

### ISSUE THREAD

**Issue by cmungall** [cthoyt/curies#17]
1. [x] priority is preserved
1. [x] chain should be case-insensitive when composing (so no "go" prefix leaks in when "GO" is present)
2. [ ] add strictness modes (some prefixes can be expected to chain with no clashes, in which case we want to throw an error if there is one, otherwise priority order is preserved)

**Comment by cthoyt** [comment]
I'm a bit hesitant about these, since they're injecting quite a bit of domain-specific logic into an otherwise totally general package, but I think providing an alternative construction algorithm with case insensitivity is a reasonable thing to implement in the package if it's labeled as such. Can you provide some specific examples of the inputs and outputs for each of these that are desired?

**Comment by cthoyt** [comment]
#19 implements a fully featured chain (that better handles prefix synonyms and URI prefix synonyms) as well as a case-insensitive variant (which can be extended for other key algorithms)

**Comment by cthoyt** [comment]
I'm not sure what the following means

>  add strictness modes (some prefixes can be expected to chain with no clashes, in which case we want to throw an error if there is one, otherwise priority order is preserved)

so I'm going to close this. Feel free to elaborate with some examples and I will be happy to re-open the issue.
