### ISSUE TITLE
Pandas dataframe standardization returns `None` columns

### ISSUE THREAD

**Issue by hrshdhgd** [cthoyt/curies#72]
From #63 

I have a similar issue. Here's my code:

```
import pyobo
from curies import get_obo_converter

obo_converter = get_obo_converter()
df = pyobo.get_sssom_df("umls", names=False)

# Remove bananas
df["object_id"] = df["object_id"].apply(lambda x: ":".join(x.split(":")[-2:]) if str(x).count(":") > 1 else x)

obo_converter.pd_standardize_curie(df, column="object_id")
print(df)
```

This gives `object_id` column to be `None`s. 

Questions:
1. I commented the code for banana removal and ran the code above. It yielded same results. (I understand the banana removal process may not be accurate but trying to get this working for now).
2. I know all rows in the `object_id` column are CURIEs. 
3. In a situation where not all but some elements  in the column of interest are not legitimate CURIEs , would this truncate all to `None`s?

Any suggestions would be super valuable!

- I'd like to add: `bioregistry_converter.pd_standardize_curie(df, column="object_id")` does yield results but I specifically need OBO format for prefixes.
- `get_monarch_converter()` returns `None`s as well

**Comment by hrshdhgd** [comment]
My main motivation to go down this rabbit hole is trying to get `ncit:C77840` to standardize to `NCIT:C77840` which did not happen in its current state.

May I suggest this code:
https://github.com/cthoyt/curies/blob/e5c56d66338dbaea3d98366dd7f3010810296c7e/src/curies/api.py#L990-L1010

to be updated as 

```python
def standardize_prefix(self, prefix: str) -> Optional[str]:
        """Standardize a prefix.

        :param prefix:
            The prefix of the CURIE
        :returns:
            The standardized version of this prefix wrt this converter.
            If the prefix is not registered in this converter, returns none.

        >>> from curies import Converter, Record
        >>> converter = Converter.from_extended_prefix_map([
        ...     Record(prefix="CHEBI", prefix_synonyms=["chebi"], uri_prefix="..."),
        ... ])
        >>> converter.standardize_prefix("chebi")
        'CHEBI'
        >>> converter.standardize_prefix("CHEBI")
        'CHEBI'
        >>> converter.standardize_prefix("NOPE") is None
        True
        """
        if prefix.lower() in [k.lower() for k in self.synonym_to_prefix.keys()]:
            standardized_prefix = [v for k, v in self.synonym_to_prefix.items() if k.lower() == prefix.lower()][0]
        else:
            # default was None. Could also have a logging.info() but that would flood the console.
            standardized_prefix = prefix
        return standardized_prefix
```

This way:
- Even if there is no standardized version for a `prefix` It returns the same as before instead of `None`. I can see an argument to be made wherein `standardized_prefix` is not always the standard version.
- Makes the `prefix` case-insensitive and makes sure `.upper()` / `.lower()` / mixed case `prefix`es are still caught and standardized.

Thoughts?

**Comment by cthoyt** [comment]
@hrshdhgd besides the more general issue, I think I solved this in PyOBO. Have you upgraded to v0.10.2?

**Comment by hrshdhgd** [comment]
Awesome! Thanks Charlie.... I will upgrade this coming week

**Comment by cthoyt** [comment]
As a final note for this, we will definitely add ad-hoc text casing processing into the base functionality for this package. However, it's possible to subclass the `Converter` class and introduce various functionalities for your use case. Here are a few lighter-weight alternatives that instead focus on making a better prefix map than using the OBO one:

## Enrich with the Bioregistry

The purpose of the Bioregistry is to be the most comprehensive extended prefix map out there. Because `curies.chain` respects priority, you can enrich any prefix map with the Bioregistry and more or less get the desired results. You can accomplish being able to standardize `ncit`, which itself is missing as a prefix from the OBO converter since OBO has no synonyms and only uses `NCIT` as the prefix, by doing the following:

```python
import curies

converter = curies.chain([
    curies.get_obo_converter(),
    curies.get_bioregistry_converter(),
])
```

## Add *ad-hoc* CURIE prefix synonyms

Another alternative is you can add in the synonym you want that's not available from the OBO Converter with

```python
import curies

converter = curies.get_obo_converter()
converter.add_record(curies.Record(prefix="NCIT", prefix_synonyms=["ncit"], uri_prefix=...))
```

**Comment by hrshdhgd** [comment]
Ooh .. I like the chining better! Thanks @cthoyt !!
